[package]
name = "h4w43m"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
dirs = "5.0.1"
flexi_logger = "0.25.6"
# indicatif = "0.17.6"
log = "0.4"
owo-colors = "3.5.0"
